### ISSUE TITLE
Fill/unfill with single key?

### ISSUE THREAD

**Issue by alphapapa** [purcell/unfill#2]
Hi Steve,

I recently rediscovered this:

```elisp
(defun endless/fill-or-unfill ()
  "Like `fill-paragraph', but unfill if used twice."
  ;; From http://endlessparentheses.com/fill-and-unfill-paragraphs-with-a-single-key.html
  (interactive)
  (let ((fill-column
         (if (eq last-command 'endless/fill-or-unfill)
             (progn (setq this-command nil)
                    (point-max))
           fill-column)))
    (call-interactively #'fill-paragraph)))

(global-set-key [remap fill-paragraph]
                #'endless/fill-or-unfill)
```
I've had `unfill` installed for a while, but this is so handy, being able to hit the same key and both fill and unfill, without having to press another key to unfill.

What do you think about adding this feature to this package?  I'll send a PR if you are willing.

Thanks.

**Comment by purcell** [comment]
Erm, it has already been done, quite a while back! :-)

**Comment by purcell** [comment]
I guess you might have been using MELPA Stable, which I generally don't give much thought too, sorry -- I've tagged a fresh release of unfill for that purpose.

**Comment by alphapapa** [comment]
LOL sorry about that.  Actually I think I just hadn't upgraded unfill in a while.  Oops.  :)

**Comment by alphapapa** [comment]
Actually you were right, somehow I had installed it from stable.  Thanks.  :)
